// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRc_OaRSEmyNyG7H7c6dj4EH3BoMo0AU',
    appId: '1:1043634859358:web:bdcb67e6d1fa75e11c73cf',
    messagingSenderId: '1043634859358',
    projectId: 'chatly-26ad5',
    authDomain: 'chatly-26ad5.firebaseapp.com',
    storageBucket: 'chatly-26ad5.appspot.com',
    measurementId: 'G-H7XMWSG3SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwp307WriRZdYMOBW8Tew5mYq9bQtqtZ0',
    appId: '1:1043634859358:android:ed9b7f70f00fee431c73cf',
    messagingSenderId: '1043634859358',
    projectId: 'chatly-26ad5',
    storageBucket: 'chatly-26ad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2ROA__uF6LhVTJedkMdpSYKEuai97ig',
    appId: '1:1043634859358:ios:d25703a81c4222ac1c73cf',
    messagingSenderId: '1043634859358',
    projectId: 'chatly-26ad5',
    storageBucket: 'chatly-26ad5.appspot.com',
    androidClientId: '1043634859358-u2aas2vh9s82h6o2flehti7giabnipqc.apps.googleusercontent.com',
    iosClientId: '1043634859358-c2hg0ch9cs3l2fis5t5rsv3vu6ftoge2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl2ROA__uF6LhVTJedkMdpSYKEuai97ig',
    appId: '1:1043634859358:ios:d25703a81c4222ac1c73cf',
    messagingSenderId: '1043634859358',
    projectId: 'chatly-26ad5',
    storageBucket: 'chatly-26ad5.appspot.com',
    androidClientId: '1043634859358-u2aas2vh9s82h6o2flehti7giabnipqc.apps.googleusercontent.com',
    iosClientId: '1043634859358-c2hg0ch9cs3l2fis5t5rsv3vu6ftoge2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatly',
  );
}
